name: resend_integration_tests
version: 0.1.0
config-version: 2

profile: resend_integration_tests

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: target
clean-targets:
  - target
  - dbt_packages
  - logs

vars:
  resend_source_schema: main
  resend__using_webhook_events: true
  resend__using_api_snapshots: false

seeds:
  resend_integration_tests:
    +quote_columns: false
